### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fabiomaia** [canonical-web-and-design/anbox-cloud.io#115]
Typo in https://anbox-cloud.io/docs/reference/anbox-http-api-reference

```
"latitude":: 52.4538982,
```

**Comment by SirSamTumless** [comment]
@morphis Hi, just wanted to tag you in this.

**Comment by carkod** [comment]
@aguadoenzo can you update this in anbox docs

**Comment by aguadoenzo** [comment]
@carkod looks like it has already been fixed in the official documentation, closing this issue
