### ISSUE TITLE
Docs side navigation is not implemented correctly

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/anbox-cloud.io#116]
[The side nav](https://anbox-cloud.io/docs) contains blue links for titles. Please see [the docs](https://vanillaframework.io/docs/examples/patterns/side-navigation/default) for the correct styles.

![image](https://user-images.githubusercontent.com/9105999/90391991-f9890480-e085-11ea-9e87-363fe60f2fec.png)

**Comment by goulinkh** [comment]
@spencerbygraves This issue seems to be resolved, I just checked the nav link and it seems to have the same styling as defined in the vf docs.
Can you confirm this please?
