### ISSUE TITLE
Partners logos on home page are not HD

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/anbox-cloud.io#133]
![image](https://user-images.githubusercontent.com/40214246/95737687-feca9000-0c7f-11eb-8687-705a616beac0.png)

**Comment by carkod** [comment]
They do look sharp to me, and they have the Hi def parameter https://github.com/canonical-web-and-design/anbox-cloud.io/blob/master/templates/index.html#L126

**Comment by solazio** [comment]
Those are different images. Go a few lines below and see the ones I'm talking about are not `hi_def` https://github.com/canonical-web-and-design/anbox-cloud.io/blob/master/templates/index.html#L184

**Comment by carkod** [comment]
> Those are different images. Go a few lines below and see the ones I'm talking about are not `hi_def` https://github.com/canonical-web-and-design/anbox-cloud.io/blob/master/templates/index.html#L184

Oh yeah, you are right. Why keep some of them True and some others False? Anyway, I guess we can change them all to True

**Comment by solazio** [comment]
If you keep them `False` they are slightly smaller in size (I guess), but they look bad.
