### ISSUE TITLE
The app crashes, URL not available: demo-api.anbox-cloud.io

### ISSUE THREAD

**Issue by MusiCode1** [canonical-web-and-design/anbox-cloud.io#153]
I get stuck trying to create an invitation code.
When I try to enter http://localhost:8043/login, I get an error window.

The apparent problem is that this site https://demo-api.anbox-cloud.io does not work.
(https://check-host.net/check-http?host=https://demo-api.anbox-cloud.io)

I found the reference to this link in file [webapp/app.py](https://github.com/canonical-web-and-design/anbox-cloud.io/blob/master/webapp/app.py).

**Comment by carkod** [comment]
Hi @MusiCode1, 
Thanks for reporting this issue. The demo Anbox Cloud application is no longer supported, as the Anbox team has upgraded the APK to a new different version. You may be able to contact them through the (form)[https://anbox-cloud.io/#request-form] and ask for a developer demo.

**Comment by MusiCode1** [comment]
Maybe write about this project that does not work?
So they know.
Otherwise more people will try it, and will not understand why it does not work.
