### ISSUE TITLE
Design updated demo page

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/anbox-cloud.io#54]
Some more details will be added to the demo page
[Copydoc](https://docs.google.com/document/d/1X8r8vsbKjt4-4jjoCRGocj_HzVNeEtEjLcf85lzqSQk/edit)

**Comment by anthonydillon** [comment]
@SirSamTumless where should this go?

**Comment by SirSamTumless** [comment]
I believe this was done, so I am closing it.

**Comment by anthonydillon** [comment]
Agreed, this can be closed and further updates to the demo page will be complete as part of maintence.
