### ISSUE TITLE
Add terms acceptance to login flow

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/anbox-cloud.io#56]
```
one other point, how much work would it be to add an intermediate page in the login process where the user has to check mark terms of service and a privacy policy? Legal told us we need to have both
```

**Comment by carkod** [comment]
So I have a few options in my mind:

1. Add an additional page before login
2. SSO checkbox?
3. If we add legal terms while logging in, do we need to show an entire page and force the user to scroll to the button?
