### ISSUE TITLE
Intermediate page to accept ToS and Privacy

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/anbox-cloud.io#60]
Link Login and demo with the terms page

![Untitled Diagram](https://user-images.githubusercontent.com/14939793/73856513-790f5e80-482d-11ea-8b05-1376a5000bd1.png)

**Comment by SirSamTumless** [comment]
FYI this might not be needed if we can link the terms of service in the email with the invite code to the demo page.

**Comment by SirSamTumless** [comment]
@pmahnke This is supposed to replace Ubuntu Masters.

**Comment by carkod** [comment]
Not needed for now. Quote from legal:

> I was wondering, do you think it would be possible to include " I agree that my use of the services are subject to my adherence to, and acceptance of, the Terms of Service*, Privacy Notice and Privacy Policy." Both in the email and on the landing page (without a checkbox). Please note that it is highly likely that we will have to change this in the future but hopefully it will speed up the process for now.
