### ISSUE TITLE
Demo streaming doesn't work in Firefox

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/anbox-cloud.io#62]
I get:

https://user-images.githubusercontent.com/519935/74026010-22289700-499d-11ea-894d-98984e98e945.png

(As mentioned here: https://github.com/canonical-web-and-design/anbox-cloud.io/pull/50#issuecomment-583351785)

**Comment by carkod** [comment]
Not working on Safari either

`[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'jsonResp.metadata.stun_servers.length')
	(anonymous function) (anbox-stream-sdk.js:145)
	promiseReactionJob`

**Comment by morphis** [comment]
Only Firefox and Chrome based browsers are supported. Safari or Edge (old one) don't have a good webrtc implementation for our purposes. 

@carkod @nottrobin Can we detect the browser and display an error if it's not Firefox or Chrome?

The actual problem with Firefox seems to be coming from that the API server is still behind VPN and the ICE process fails to figure out proper candidate pairs to establish a peer-to-peer connection.

**Comment by carkod** [comment]
So I have setTimeout on `jsonResp.metadata.stun_servers`.

I guess there is some promise here that is taking time to process? (around line 144)

            if (jsonResp.metadata.stun_servers.length > 0)
                setInterval(3000, this._options.stunServers.concat(jsonResp.metadata.stun_servers))
            this._connectSignaler(jsonResp.metadata.websocket_url);

**Comment by carkod** [comment]
So we are still getting Stun_Server errors. Quoting from @morphis 
> it's a service side timing problem
> nothing on the website as we miss to transfer STUN servers sometimes

1. One solution that we have discussed previously was to ask users to switch to Chrome?
2. Sometimes after refreshing it works
