### ISSUE TITLE
anbox-cloud.io/login?invitation_code=xxx doesn't redirect to anbox-cloud.io/demo

### ISSUE THREAD

**Issue by morphis** [canonical-web-and-design/anbox-cloud.io#69]
When using anbox-cloud.io/login?invitation_code=xxx with a valid invitation code I never get redirected to anbox-cloud.io/demo but anbox-cloud.io. This is the current behavior on staging.anbox-cloud.io

After successful authentication and authorization anbox-cloud.io/login?invitation_code=xxx should redirect to the demo page at anbox-cloud.io/demo

**Comment by carkod** [comment]
None of our sites do that, I was told to redirect to `/demo` we need to do `anbox-cloud.io/login?invitation_code=xxx&next=/demo`

**Comment by morphis** [comment]
Fine for me. Thanks!
