### ISSUE TITLE
Login process can't deal with expired tokens

### ISSUE THREAD

**Issue by morphis** [canonical-web-and-design/anbox-cloud.io#70]
I've logged into staging.anbox-cloud.io yesterday with a valid invitation code but not able to login again today and only get

```
401: Unauthorised
authentication failed: invalid token.
```

when trying to access staging.anbox-cloud.io/demo.

As the login tokens given out by the demo service expire after 24 hours it looks like the UI doesn't call `/1.0/login` again to generate a new token.

**Comment by morphis** [comment]
I can reproduce this with latest master which I used yesterday to login. When I clear all cookies of the site the login is performed again and I get access to the demo page.

**Comment by nottrobin** [comment]
According to @carkod, this wasn't truly fixed by #72. Reopening.
