### ISSUE TITLE
Disable streaming on unsupported browsers

### ISSUE THREAD

**Issue by aguadoenzo** [canonical-web-and-design/anbox-cloud.io#88]
A check was added to the stream SDK to prevent streaming on unsupported browsers.
We need to have a message telling users to use a supported browser when that occurs

the following error is thrown if a browser is unsupported
`throw new Error("unsupported browser");`

**Comment by carkod** [comment]
@deadlight do we have anything in Vanilla to do this? I can think of a dozen ways to show this message (pop up, cookie style on top, bottom corner, modal...) or we could even reuse your pop-up when browser is not supported?

**Comment by anthonydillon** [comment]
@carkod I would suggest using a notification: https://docs.vanillaframework.io/patterns/notification

**Comment by deadlight** [comment]
@carkod yeah, I would use the existing error message on the stream

**Comment by carkod** [comment]
Old sdk not supported anymore.
